pixel4a:
  phonenum: 07084075832

apple:
  password: KassyKotaro98

google:
  email: kotaro11kassy@gmail.com
  password: Kassy98Kotaro11

github:
  password: Kassy-9811
  
lastpass:
  password: Kotaro98Kassy

yahoo:
  email: kassy11kotaro@yahoo.co.jp

amazon:
  password: kassy11

rakuten:
  password: kassy1198

kitnet-wifi:
  password: 123a456b789c012d345e678f90

paypal:
  password: Kotaro-9811

sumishin:
  id: kassy11
  password: Kassy98Kotarokk
  web-transaction: Kotaro-1198kotaro

kyotobank:
  login: KOTARO9811
  riyokaishi: 0917

## For LisB intern

google:
  email: kotaro.kashihara.lisb@gmail.com
  password: Vw(7DN#s

direct:
  email: kotaro.kashihara.lisb@gmail.com
  password: kassy-kotaro-direct

youtrack:
  password: kotaro-Kassy11
    

